# Generated by Django 2.2.5 on 2019-10-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0002_auto_20190916_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=750)),
            ],
        ),
    ]
