# Generated by Django 2.2.5 on 2019-10-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0010_auto_20191011_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ss',
            name='parrent',
        ),
        migrations.AddField(
            model_name='ss',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parrent', to='resttest.Ss'),
        ),
    ]
