# Generated by Django 2.2.5 on 2019-10-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0011_auto_20191011_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ss',
            options={'ordering': ['children']},
        ),
        migrations.AlterModelTable(
            name='ss',
            table='categories',
        ),
    ]
