# Generated by Django 2.2.5 on 2019-10-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0012_auto_20191011_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ss',
            options={'ordering': ['children__id']},
        ),
    ]
