# Generated by Django 2.2.5 on 2019-10-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0013_auto_20191011_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ss',
            options={},
        ),
        migrations.AlterModelTable(
            name='ss',
            table=None,
        ),
    ]
