# Generated by Django 2.2.5 on 2019-10-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0014_auto_20191011_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('children', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ss',
            name='children',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resttest.Children'),
            preserve_default=False,
        ),
    ]
