# Generated by Django 2.2.5 on 2019-10-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0015_auto_20191011_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ss',
            name='children',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='Ss',
        ),
    ]
