# Generated by Django 2.2.5 on 2019-10-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0018_auto_20191011_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='children',
        ),
    ]
