# Generated by Django 2.2.5 on 2019-10-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0019_remove_children_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ss',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parrent', to='resttest.Children'),
        ),
    ]
