# Generated by Django 2.2.5 on 2019-10-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0020_auto_20191011_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ss',
            name='children',
        ),
        migrations.AddField(
            model_name='ss',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='resttest.Ss'),
        ),
        migrations.AlterField(
            model_name='ss',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ss',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterModelTable(
            name='ss',
            table='Categories',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
    ]
